class Node:
    def __init__(self, name: str): ...
    def create_publisher(self, msg_type, topic: str, qos_profile: int): ...
    def create_subscription(self, msg_type, topic: str, callback, qos_profile: int): ...
    def create_timer(self, timer_period_sec: float, callback): ...
    def get_logger(self): ...
    def destroy_node(self): ...
